- name: deleting a directory if its already exist
  ansible.builtin.file:
    path: "{{app_location}}"
    state: absent
  ignore_errors: true
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{app_location}}"
    state: directory

# unarchive will directly download from the net and also unzip it in particular locaton with url module
- name: "downloading {{component}} file pasting in location"
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{component}}-v2.zip"
    dest: "{{app_location}}"
    remote_src: yes