- name: "frontend configuration"
  hosts: frontend
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: "starting services"
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      src: /usr/share/nginx/html
      state: absent

  - name: Download frontend files
    ansible.builtin.get_url:
      url:  https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: Copy a "frontend.conf" file 
    ansible.builtin.copy:
      src: expence.conf
      dest: /etc/nginx/default.d/expense.conf
      #remote_src: yes

  - name: srestarted the nginx
    ansible.builtin.service:
      name: nginx
      state: restarted