- name: "frontend configuration"
  hosts: frontend
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx server
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
    ignore_errors: true

  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: Download frontend files
    ansible.builtin.get_url:
      url:  https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: create html directory
    ansible.builtin.file:
      path: /etc/nginx/default.d/expense.conf
      state: absent

  - name: create html directory
    ansible.builtin.file:
      path: /etc/nginx/default.d
      state: directory

  - name: Copy a "frontend.conf" file 
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d
      #remote_src: yes

  - name: restarted the nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
    ignore_errors: true