- name: "creating ec2 instances"
  hosts: local
  connection: local
  vars:
   subnet_id: subnet-0db7f96b56d8185f0
   sec_group: sg-071b3d7ca661a90ab
   ami_id: ami-09c813fb71547fc4f
   zone: kondarao.online
   intances:
   - mysql
   - backend
   - frontend
  tasks:
  - name: ansible to install boto3 and botocore
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      executable: pip3.9
  
  - name: "creating ec2 instances"
    amazon.aws.ec2_instance:
      name: "{{item}}"
      vpc_subnet_id: "{{subnet_id}}"
      instance_type: t3.small
      image_id: "{{ami_id}}"
      wait: true
    loop: "{{intances}}"
    register: instance_details

  - name: "printing server details"
    ansible.builtin.debug:
      msg: "{{instance_details}}"
  
  - name: "creating route 53 records for private ip"
    amazon.aws.route53:
      state: present
      zone: "{{zone}}"
      record: "{{item.item}}.{{zone}}"
      type: A
      ttl: 1
      value: "{{item.instances[0].private_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{instance_details.results}}"

  - name: "creating route 53 records for public ip"
    amazon.aws.route53:
      state: present
      zone: "{{zone}}"
      record: "{{zone}}"
      type: A
      ttl: 1
      value: "{{item.instances[0].public_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{instance_details.results}}"
    when: item.item == "frontend"